### ISSUE TITLE
Scanner Problem

### ISSUE THREAD

**Issue by ghost** [ccldev/v2-compile-sytems#1]
`#include lib.cl2

var Scanner = (java.util.Scanner);
var scanner = Scanner(System.in);
var read = scanner.nextLine;

var test = read();`

When i do this, it response with this:
`Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(Unknown Source)
        at ccl.csy.value.ValueCompiler.act(ValueCompiler.java:16)
        at ccl.csy.value.param.ParameterParser.compileParsed(ParameterParser.java:28)
        at ccl.csy.value.param.ParameterParser.compile(ParameterParser.java:21)
        at ccl.csy.value.dotype.CCLInvoke.getBase(CCLInvoke.java:52)
        at ccl.csy.value.todo.TodoCompiler.compileTodo(TodoCompiler.java:10)
        at ccl.csy.value.ValueCompiler.act(ValueCompiler.java:34)
        at ccl.csy.variable.VariableCompileSystem.compile(VariableCompileSystem.java:22)
        at ccl.v2.sys.CompileSystems.use(CompileSystems.java:13)
        at ccl.v2.cat.CodeSnippet.compiled(CodeSnippet.java:19)
        at ccl.dev.use.CCL.compile(CCL.java:84)
        at ccl.dev.test.TESt.main(TESt.java:22)`

**Comment by NetLamp-Y** [comment]
This Bug is fixed in the new Version (0.2.1).
Thanks for reporting :)
